modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "enchant_limiter"
version = "${version}"
displayName = "Enchant Limiter"
authors = "Daedelus"
description = '''
Limit the number of enchantments on an item.
'''
logoFile = "icon.png"

[[dependencies.enchant_limiter]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.enchant_limiter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "enchant_limiter.mixins.json"
